/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Sun Sep 11 14:59:14 2016
 * --------------------------------------------------------
 *
 */
#include "user_model.h"
#include "mbs_xml_reader.h"
#include "mbs_load_xml.h"
#include "useful_functions.h"

// ============================================================ //


UserModel* mbs_new_user_model() 
{
    UserModel* um;
    um = (UserModel*)malloc(sizeof(UserModel));
    um->Rolling.State_var = get_ivec_1(12);
    um->Rolling.State_var[0] = 12;
 
 
    return um;
}

void mbs_delete_user_model(UserModel* um) 
{
    free_ivec_0(um->Rolling.State_var);
    free(um);
}

 void mbs_load_user_model_xml(MDS_gen_strct* gen, UserModel* um) 
{

    int ind;
    int ind_state_value = 1;

    for(ind=0; ind<gen->user_models->user_model_list[0]->parameter_list[0]->n_value; ind++)
    {
        um->Rolling.State_var[ind+1] = ind_state_value;
        ind_state_value++;
    }
 
 
}

// ============================================================ //
 
