/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Sun Sep 11 14:59:14 2016
 * --------------------------------------------------------
 *
 */
#ifndef USERMODEL_h
#define USERMODEL_h

//#include "lut.h"


#include "mbs_user_interface.h"
// ============================================================ //


struct UserModel 
{
    struct Rolling{
        int* State_var;
        // index of the corresponding values in MBSdataStruct->ux/uxd/ux0
    } Rolling;
 
    struct user{
        void* cpp_interface;        // pointer must be initialized and freed by the user
    } user;
 
};

// ============================================================ //
 
# endif
