/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Sun Sep 11 14:59:14 2016
 * --------------------------------------------------------
 *
 */
#ifndef USER_HARD_PARAM_h
#define USER_HARD_PARAM_h

// ============================================================ //


// gravity
#define G_3 -9.81

// mass
#define M_3 2.5
#define M_4 0.1
#define M_5 0.1
#define M_6 0.5
#define M_9 2.5
#define M_10 0.1
#define M_11 0.1
#define M_12 0.5
#define M_15 2.5
#define M_16 0.1
#define M_17 0.1
#define M_18 0.5
#define M_21 2.5
#define M_22 0.1
#define M_23 0.1
#define M_24 0.5

// center of mass
#define L_1_3 0.05
#define L_3_3 0.05
#define L_1_9 0.05
#define L_3_9 0.05
#define L_1_15 0.05
#define L_3_15 0.05
#define L_1_21 0.05
#define L_3_21 0.05

// inertia
#define IN_1_3 0.001
#define IN_5_3 0.001
#define IN_9_3 0.001
#define IN_1_4 0.0001
#define IN_5_4 0.0005
#define IN_9_4 0.0001
#define IN_1_5 0.0001
#define IN_5_5 0.0005
#define IN_9_5 0.0001
#define IN_1_6 0.0001
#define IN_5_6 0.0001
#define IN_9_6 0.0001
#define IN_1_9 0.001
#define IN_5_9 0.001
#define IN_9_9 0.001
#define IN_1_10 0.0001
#define IN_5_10 0.0005
#define IN_9_10 0.0001
#define IN_1_11 0.0001
#define IN_5_11 0.0005
#define IN_9_11 0.0001
#define IN_1_12 0.0001
#define IN_5_12 0.0001
#define IN_9_12 0.0001
#define IN_1_15 0.001
#define IN_5_15 0.001
#define IN_9_15 0.001
#define IN_1_16 0.0001
#define IN_5_16 0.0005
#define IN_9_16 0.0001
#define IN_1_17 0.0001
#define IN_5_17 0.0005
#define IN_9_17 0.0001
#define IN_1_18 0.0001
#define IN_5_18 0.0001
#define IN_9_18 0.0001
#define IN_1_21 0.001
#define IN_5_21 0.001
#define IN_9_21 0.001
#define IN_1_22 0.0001
#define IN_5_22 0.0005
#define IN_9_22 0.0001
#define IN_1_23 0.0001
#define IN_5_23 0.0005
#define IN_9_23 0.0001
#define IN_1_24 0.0001
#define IN_5_24 0.0001
#define IN_9_24 0.0001

// body point
#define DPT_3_1 0.2
#define DPT_2_2 -0.1125
#define DPT_3_2 0.03
#define DPT_2_3 0.1125
#define DPT_3_3 0.03
#define DPT_1_4 0.083
#define DPT_3_4 0.16
#define DPT_3_5 0.03
#define DPT_2_6 -0.1125
#define DPT_3_6 0.03
#define DPT_2_7 0.1125
#define DPT_3_7 0.03
#define DPT_1_8 0.083
#define DPT_3_8 0.16
#define DPT_3_9 0.03
#define DPT_2_10 -0.1125
#define DPT_3_10 0.03
#define DPT_2_11 0.1125
#define DPT_3_11 0.03
#define DPT_1_12 0.083
#define DPT_3_12 0.16
#define DPT_3_13 0.03
#define DPT_2_14 -0.1125
#define DPT_3_14 0.03
#define DPT_2_15 0.1125
#define DPT_3_15 0.03
#define DPT_1_16 0.083
#define DPT_3_16 0.16
#define DPT_3_17 0.03

// ============================================================ //

# endif
