/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Sun Sep 11 14:59:14 2016
 * --------------------------------------------------------
 *
 */
#ifndef USER_ALL_ID_h
#define USER_ALL_ID_h

// ============================================================ //


// joint

#define FJ_T1_robot_B_id 1
#define FJ_T2_robot_B_id 2
#define FJ_R3_robot_B_id 3
#define Right_wheel_joint_B_id 4
#define Left_wheel_joint_B_id 5
#define Tower_joint_B_id 6
#define FJ_T1_robot_R_id 7
#define FJ_T2_robot_R_id 8
#define FJ_R3_robot_R_id 9
#define Right_wheel_joint_R_id 10
#define Left_wheel_joint_R_id 11
#define Tower_joint_R_id 12
#define FJ_T1_robot_Y_id 13
#define FJ_T2_robot_Y_id 14
#define FJ_R3_robot_Y_id 15
#define Right_wheel_joint_Y_id 16
#define Left_wheel_joint_Y_id 17
#define Tower_joint_Y_id 18
#define FJ_T1_robot_W_id 19
#define FJ_T2_robot_W_id 20
#define FJ_R3_robot_W_id 21
#define Right_wheel_joint_W_id 22
#define Left_wheel_joint_W_id 23
#define Tower_joint_W_id 24


// body

#define Main_frame_B_id 3
#define Right_wheel_B_id 4
#define Left_wheel_B_id 5
#define Tower_B_id 6
#define Main_frame_R_id 9
#define Right_wheel_R_id 10
#define Left_wheel_R_id 11
#define Tower_R_id 12
#define Main_frame_Y_id 15
#define Right_wheel_Y_id 16
#define Left_wheel_Y_id 17
#define Tower_Y_id 18
#define Main_frame_W_id 21
#define Right_wheel_W_id 22
#define Left_wheel_W_id 23
#define Tower_W_id 24


// point

#define Ground_level_anchor_id 0
#define Right_wheel_anchor_B_id 1
#define Left_wheel_anchor_B_id 2
#define Tower_anchor_B_id 3
#define Force_anchor_B_id 4
#define Right_wheel_anchor_R_id 5
#define Left_wheel_anchor_R_id 6
#define Tower_anchor_R_id 7
#define Force_anchor_R_id 8
#define Right_wheel_anchor_Y_id 9
#define Left_wheel_anchor_Y_id 10
#define Tower_anchor_Y_id 11
#define Force_anchor_Y_id 12
#define Right_wheel_anchor_W_id 13
#define Left_wheel_anchor_W_id 14
#define Tower_anchor_W_id 15
#define Force_anchor_W_id 16


// sensor



// extforce

#define Fsens_robot_B_id 1
#define Fsens_robot_R_id 2
#define Fsens_robot_Y_id 3
#define Fsens_robot_W_id 4


// links



// ============================================================ //

# endif
